use super::constant::Constant;

#[derive(Debug, PartialEq)]
pub enum Instruction {
    Add,
    Minus,
    Mul,
    Div,
    Eq,
    GreaterEq,
    Greater,
    LessEq,
    Less,
    NotEq,
    End,
    Return,
    LoadList,
    And,
    Or,
    Not,
    Clone,
    LoadTuple,
    LoadFromList,
    LoadFromTuple(i32),
    Store(String),
    Assign(String),
    AssignListIndex(i32),
    AssignTupleIndex(i32),
    LoadConst(Constant),
    LoadVar(String),
    Closure(String),
    CallDynamic { args: i32 },
    Call { function: String, args: usize },
}
